name: msh_esiee_app
description: une application de quiz dans le cadre d&#x27;un projet MSH Esiee Paris

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/dataimage.png
    - assets/images/webcam.jpg
    - assets/images/facebookalgorithm.jpg
    - assets/images/binaire.jpg
    - assets/images/Arduino_Uno.jpg
    - assets/images/supplychain.jpg
    - assets/images/model-s-performance.jpg
    - assets/images/thomaspesquet.jpg
    - assets/images/panneauxsolaires.jpg
    - assets/images/motdepasse.jpg
    - assets/images/dataviz.jpg
    - assets/images/algo.jpg
    - assets/images/souder.jpg
    - assets/images/opti.jpg
    - assets/images/tonystark.jpg
    - assets/images/helping-hand.jpg
    - assets/images/eolienne.jpg
    - assets/images/localhost.png
    - assets/images/ml.jpg
    - assets/images/python.jpg
    - assets/images/tore.jpg
    - assets/images/excel.jpeg
    - assets/images/regulateur.jpg
    - assets/images/donnemedicale.jpg
    - assets/images/ecologie.jpg
    - assets/images/BIO.jpg
    - assets/images/cyber.jpg
    - assets/images/datascience.jpg
    - assets/images/ENE.jpg
    - assets/images/GI.jpg
    - assets/images/INFO.jpg
    - assets/images/SE.jpg
    - assets/images/SEI.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Medium.ttf
          weight: 400

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
